/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import petshop.CategoryDAO;
import petshop.Product;
import petshop.ProductDAO;
import petshop.DatabaseConection;
import java.sql.*;

/*
 * @author ywani
 */




public class ViewAllProducts extends javax.swing.JFrame {
    private DefaultTableModel tableModel;
    private DatabaseConection DBC;
    private DefaultListModel categoryListModel;
    private CategoryDAO categoryDAO;
    /**
     * Creates new form ViewAllProducts
     */
    public ViewAllProducts() {
        
        DBC = new DatabaseConection();
        categoryDAO = new CategoryDAO(DBC);
        initComponents();
        loadCategory();
        //loadProducts("All");
        catogeris.setSelectedIndex(0);
    }
    
    public void loadCategory(){
        categoryListModel = new DefaultListModel();
        catogeris.setModel(categoryListModel);
        categoryListModel.clear();
        categoryListModel.addElement("All"); // Default option to show all products
        List<String> categories = categoryDAO.getCategories();
        if (categories != null) {
            for (String category : categories) {
                categoryListModel.addElement(category);
            }
        }
        
    }
    
    /*public void loadProducts(){
         tableModel = (DefaultTableModel) productTable.getModel();
        tableModel.setRowCount(0);  // Clear table before reloading
        List<Product> products;
        
        
        ProductDAO productDAO = new ProductDAO(DBC);
        
        products = productDAO.getProducts();
       
        for(Product p:products){
            tableModel.addRow(new Object[]{p.getProductId(), p.getName(),p.getCategory(), p.getPrice(), p.getQuantity()});
        }
        
    }*/
    private void loadProducts(String category) {
        tableModel = (DefaultTableModel) productTable.getModel();
        tableModel.setRowCount(0);  // Clear table before reloading
        List<Product> products;
         int categoryId = categoryDAO.getCategoryId(category);
         
         ProductDAO productDAO = new ProductDAO(DBC);
       
         if (category.equals("All")) {
             products = productDAO.getProducts(); 
         } else {
             products = productDAO.getProductsByCategory(categoryId);
         }

         for (Product p : products) {
             tableModel.addRow(new Object[]{p.getProductId(), p.getName(), p.getCategory(), p.getPrice(), p.getQuantity()});
         }
    }
/**
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextPaneSearch = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        catogeris = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setText("View All Pruducts");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 340, -1));

        productTable.setBackground(new java.awt.Color(204, 255, 204));
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Name", "Category", "Quentity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(productTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 475, 327));

        TextPaneSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane2.setViewportView(TextPaneSearch);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 151, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("Search");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 255), null, null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 66, -1));

        catogeris.setBackground(new java.awt.Color(204, 255, 204));
        catogeris.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        catogeris.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Food", "Grooming", "Toys", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        catogeris.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                catogerisValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(catogeris);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 77, 130, 303));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 255));
        jButton3.setText("< BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 130, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                         
       String searchprod=TextPaneSearch.getText();
        
      DatabaseConection db2=new DatabaseConection();
        Connection conn=db2.getConncetion();
        
       
        
        String sql = "SELECT * FROM product where ProductName like ?";
        
        try(PreparedStatement stmt = conn.prepareStatement(sql)){
            stmt.setString(1,"%"+searchprod+"%");
            ResultSet rs = stmt.executeQuery();
            
            DefaultTableModel modelTable = (DefaultTableModel) productTable.getModel();
            modelTable.setRowCount(0);
            
            while(rs.next())
            {
                //String role = rs.getString("role");
                modelTable.addRow(new Object[]{rs.getInt("ProductID"), rs.getString("ProductName"), rs.getString("CategoryID"), rs.getInt("Quantity"), rs.getFloat("Price")});
                //System.out.println(rs.getString("Name")+ " "+rs.getString("Category")+" "+rs.getString("Quantity")+" "+rs.getString("Price"));
            }
            
            
            
        } catch (SQLException e){
            e.printStackTrace();
        }  
       
       
    }                                        

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {                                      
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void catogerisValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_catogerisValueChanged
           TextPaneSearch.setText("");
        if (!evt.getValueIsAdjusting()) {
                    String selectedCategory = catogeris.getSelectedValue();
                    loadProducts(selectedCategory);
        }        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_catogerisValueChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAllProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane TextPaneSearch;
    private javax.swing.JList<String> catogeris;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable productTable;
    // End of variables declaration//GEN-END:variables
}
